In [ ]:
# Внимание!!! Важно, что бы файлы с данными и исполняемый файл находились в одной папке, 
# тогда пути к тестовым и тренировочным наборам будут содержать только имена файлов.
# 
# В пути к тренировочным и тестовым данным запрежается использовать абсалютную адресацию, 
# то есть адресацию, в которой присутствуют имена папок. Путь должен содержать только имя файла.
#
# Напоминание: под моделью машинного обучения понимаются все действия с исходными данными, 
# которые необходимо произвести, что бы сопоставить признаки целевому значению.

### Область работы 1 (библиотеки)

In [ ]:
# Данный блок в области 1 НЕ выполняется преподавателем
# 
# данный блок предназначен только для подключения необходимых библиотек
# запрещается подключать библиотеки в других блоках
#
# установка дополнительных библиотек размещается прямо здесь (обязательно закоментированы)
#
# pip install

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import RobustScaler, OneHotEncoder, PowerTransformer, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_log_error, make_scorer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.compose import TransformedTargetRegressor

### Область работы 2 (поиск  модели .... )

In [13]:
# Данный блок(и) НЕ выполняются преподавателем в области 2
# блок(и) предназначены для поиска лучшей модели 
# должен быть понятен и очевиден отбор параметров модели
# 
# Запрещается размещать данные блоки за пределами обасти 2
# Все блоки данной области должны быть выполнены
#
# ЗАПРЕЩАЕТСЯ ИСПОЛЬЗОВАТЬ ТЕСТОВЫЙ НАБОР
#
# Путь к тренировочному набору
# 

path_train = 'train.csv' # содержит только имя файла, без имен папок !!!

In [14]:
df = pd.read_csv(path_train)
df

,size,color,fancy_color_dominant_color,fancy_color_secondary_color,fancy_color_overtone,fancy_color_intensity,clarity,cut,symmetry,polish,...,meas_length,meas_width,meas_depth,girdle_min,girdle_max,culet_condition,fluor_color,fluor_intensity,total_sales_price,eye_clean
0,0.76,D,NaN,NaN,NaN,NaN,I1,Excellent,Excellent,Excellent,...,6.02,6.04,3.55,TN,M,NaN,NaN,NaN,3712,NaN
1,1.00,H,NaN,NaN,NaN,NaN,VVS1,Very Good,Excellent,Excellent,...,6.27,6.32,4.03,STK,TK,NaN,NaN,NaN,9717,NaN
2,0.30,F,NaN,NaN,NaN,NaN,VS1,Very Good,Very Good,Very Good,...,4.33,4.36,2.60,XTN,M,NaN,NaN,NaN,954,NaN
3,0.30,D,NaN,NaN,NaN,NaN,SI1,Excellent,Very Good,Excellent,...,4.24,4.29,2.67,STK,STK,NaN,NaN,Faint,858,NaN
4,0.32,F,NaN,NaN,NaN,NaN,VS1,Excellent,Excellent,Excellent,...,4.39,4.40,2.73,M,STK,NaN,NaN,NaN,1150,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61440,0.40,D,NaN,NaN,NaN,NaN,SI2,Excellent,Excellent,Excellent,...,4.67,4.71,2.95,NaN,NaN,NaN,NaN,Faint,1188,NaN
61441,0.30,D,NaN,NaN,NaN,NaN,VVS2,Excellent,Excellent,Excellent,...,4.27,4.30,2.64,M,STK,NaN,Blue,Medium,992,Yes
61442,0.32,G,NaN,NaN,NaN,NaN,VS2,Excellent,Excellent,Excellent,...,4.42,4.44,2.68,M,TK,NaN,Blue,Medium,1008,NaN
61443,0.60,H,NaN,NaN,NaN,NaN,VS2,Excellent,Excellent,Excellent,...,5.35,5.37,3.39,NaN,NaN,NaN,NaN,NaN,3730,NaN
61444,0.50,G,NaN,NaN,NaN,NaN,VS1,Very Good,Very Good,Very Good,...,4.99,5.02,3.14,STK,TK,NaN,NaN,Strong,2502,NaN

In [15]:
drop_cols = [
    'fancy_color_dominant_color', 'fancy_color_secondary_color', 
    'fancy_color_overtone', 'fancy_color_intensity',
    'culet_condition', 'fluor_color'
]
df = df.drop(columns=drop_cols, errors='ignore')
df

,size,color,clarity,cut,symmetry,polish,depth_percent,table_percent,meas_length,meas_width,meas_depth,girdle_min,girdle_max,fluor_intensity,total_sales_price,eye_clean
0,0.76,D,I1,Excellent,Excellent,Excellent,58.9,60.0,6.02,6.04,3.55,TN,M,NaN,3712,NaN
1,1.00,H,VVS1,Very Good,Excellent,Excellent,63.9,58.0,6.27,6.32,4.03,STK,TK,NaN,9717,NaN
2,0.30,F,VS1,Very Good,Very Good,Very Good,59.9,59.0,4.33,4.36,2.60,XTN,M,NaN,954,NaN
3,0.30,D,SI1,Excellent,Very Good,Excellent,62.7,58.0,4.24,4.29,2.67,STK,STK,Faint,858,NaN
4,0.32,F,VS1,Excellent,Excellent,Excellent,62.0,59.0,4.39,4.40,2.73,M,STK,NaN,1150,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61440,0.40,D,SI2,Excellent,Excellent,Excellent,62.9,56.0,4.67,4.71,2.95,NaN,NaN,Faint,1188,NaN
61441,0.30,D,VVS2,Excellent,Excellent,Excellent,61.7,61.0,4.27,4.30,2.64,M,STK,Medium,992,Yes
61442,0.32,G,VS2,Excellent,Excellent,Excellent,60.4,57.0,4.42,4.44,2.68,M,TK,Medium,1008,NaN
61443,0.60,H,VS2,Excellent,Excellent,Excellent,63.2,55.0,5.35,5.37,3.39,NaN,NaN,NaN,3730,NaN
61444,0.50,G,VS1,Very Good,Very Good,Very Good,62.8,56.0,4.99,5.02,3.14,STK,TK,Strong,2502,NaN

In [16]:
# проверка дубликатов
print("Количество дубликатов:", df.duplicated().sum())
df = df.drop_duplicates()

Количество дубликатов: 0

In [17]:
num_features = [
    'size', 'depth_percent', 'table_percent', 
    'meas_length', 'meas_width', 'meas_depth'
]
cat_features = [
    'color', 'clarity', 'cut', 'symmetry', 'polish', 
    'girdle_min', 'girdle_max', 'fluor_intensity', 'eye_clean'
]

In [18]:
X = df.drop(columns=['total_sales_price'])
y = df['total_sales_price']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33
)

In [19]:
num_transformer = Pipeline(steps=[
    ('imputer', IterativeImputer(max_iter=20)),
    ('poly', PolynomialFeatures(2, include_bias=False)),
    ('scaler', RobustScaler())
])

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))
])

In [20]:
CT = ColumnTransformer([
    ('num', num_transformer, num_features),
    ('cat', cat_transformer, cat_features)
]).set_output(transform='pandas')

In [21]:
pipeline = Pipeline(steps=[
    ('preproc', CT),
    ('estimator', SVR())
])

model_target = TransformedTargetRegressor(
    regressor=pipeline,
    transformer=PowerTransformer(method='yeo-johnson')
)

def msle_scorer(y_true, y_pred):
    return -mean_squared_log_error(y_true, np.maximum(y_pred, 0))

score_msle = make_scorer(mean_squared_log_error, greater_is_better=False)

# Обучение
model_target.fit(X_train, y_train)
y_pred = model_target.predict(X_test)

msle = mean_squared_log_error(y_test, np.maximum(y_pred, 0))
print(f"Mean Squared Logarithmic Error (MSLE): {msle:.6f}")

Mean Squared Logarithmic Error (MSLE): 0.009086

In [12]:
df_test = pd.read_csv('test.csv')
df_test = df_test.drop(columns=drop_cols, errors='ignore')

pred_test = model_target.predict(df_test)